import * as Shape from './SimpleShapes.jsx'

export const Workspace = () => (
    <group position={[2, 3, 0]}>
        <Shape.Baseplate/>
        // Autogenerated by export script. Time: 1760298748
        <Shape.RectCollider
            position={[24.5000, 3.25, -32.50]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[24.5000, 6.00, -32.50]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-16.0000, 3.25, 8.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-16.0000, 6.00, 8.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-31.5000, 3.25, 24.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-31.5000, 6.00, 24.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[27.5000, 3.25, 12.50]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[27.5000, 6.00, 12.50]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-11.5000, 3.25, 59.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-11.5000, 6.00, 59.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[75.5000, 3.25, 100.50]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[75.5000, 6.00, 100.50]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[59.5000, 3.25, 42.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[59.5000, 6.00, 42.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[47.0000, 3.25, -16.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[47.0000, 6.00, -16.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[42.0000, 3.25, 1.50]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[42.0000, 6.00, 1.50]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-20.5000, 3.25, -27.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-20.5000, 6.00, -27.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-22.0000, 3.25, -5.50]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-22.0000, 6.00, -5.50]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[23.0000, 3.25, 48.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[23.0000, 6.00, 48.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[39.0000, 3.25, 24.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[39.0000, 6.00, 24.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-5.0000, 3.25, -14.50]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-5.0000, 6.00, -14.50]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-9.5000, 3.25, 31.00]}
            size={[1.0000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-9.5000, 6.00, 31.00]}
            size={[2.5000, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[9.5000, 4.37, 27.00]}
            size={[12.0000, 6.75, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[11.7500, 3.37, 28.25]}
            size={[2.5000, 4.75, 1.00]}
            color={"#444e61"}/>
        <Shape.Rect
            position={[7.3750, 8.00, 27.00]}
            size={[6.2500, 0.50, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[3.2500, 1.87, 27.50]}
            size={[2.5000, 1.75, 2.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[4.0000, 1.62, 25.75]}
            size={[1.0000, 1.25, 2.00]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[11.2500, 1.37, 29.00]}
            size={[3.5000, 0.75, 2.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[15.0000, 1.37, 26.00]}
            size={[2.0000, 0.75, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[12.2500, 2.12, 28.75]}
            size={[2.5000, 2.25, 2.00]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[3.5000, 2.62, 26.00]}
            size={[1.0000, 3.25, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[6.0000, 1.62, 28.00]}
            size={[3.0000, 1.25, 0.50]}
            color={"#444e61"}/>
        <Shape.Rect
            position={[11.7500, 7.87, 27.25]}
            size={[2.5000, 0.25, 1.00]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[15.5000, 1.87, 26.50]}
            size={[2.0000, 1.75, 1.50]}
            color={"#444e61"}/>
        <Shape.Rect
            position={[24.7713, 1.33, 7.30]}
            size={[0.2231, 0.67, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[24.7713, 1.77, 7.30]}
            size={[0.2231, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[24.7713, 1.75, 7.30]}
            size={[0.2231, 0.18, 0.67]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[24.7713, 1.75, 7.30]}
            size={[0.6692, 0.18, 0.22]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[27.8415, 1.38, 5.23]}
            size={[0.2392, 0.72, 0.24]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[27.8415, 1.86, 5.23]}
            size={[0.2392, 0.24, 0.24]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[27.8415, 1.83, 5.23]}
            size={[0.2392, 0.19, 0.72]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[27.8415, 1.83, 5.23]}
            size={[0.7176, 0.19, 0.24]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[24.2183, 1.32, 4.16]}
            size={[0.2229, 0.67, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[24.2183, 1.77, 4.16]}
            size={[0.2229, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[24.2183, 1.75, 4.16]}
            size={[0.2229, 0.18, 0.67]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[24.2183, 1.75, 4.16]}
            size={[0.6686, 0.18, 0.22]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-2.5670, 1.31, -2.97]}
            size={[0.2193, 0.66, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-2.5670, 1.75, -2.97]}
            size={[0.2193, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-2.5670, 1.73, -2.97]}
            size={[0.2193, 0.18, 0.66]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[-2.5670, 1.73, -2.97]}
            size={[0.6578, 0.18, 0.22]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[-0.2267, 1.38, -5.95]}
            size={[0.2398, 0.72, 0.24]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-0.2267, 1.86, -5.95]}
            size={[0.2398, 0.24, 0.24]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-0.2267, 1.84, -5.95]}
            size={[0.2398, 0.19, 0.72]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-0.2267, 1.84, -5.95]}
            size={[0.7195, 0.19, 0.24]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-4.9974, 1.38, -4.59]}
            size={[0.2389, 0.72, 0.24]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-4.9974, 1.85, -4.59]}
            size={[0.2389, 0.24, 0.24]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-4.9974, 1.83, -4.59]}
            size={[0.2389, 0.19, 0.72]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-4.9974, 1.83, -4.59]}
            size={[0.7166, 0.19, 0.24]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[21.7970, 1.32, 23.02]}
            size={[0.2216, 0.66, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[21.7970, 1.76, 23.02]}
            size={[0.2216, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[21.7970, 1.74, 23.02]}
            size={[0.2216, 0.18, 0.66]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[21.7970, 1.74, 23.02]}
            size={[0.6649, 0.18, 0.22]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[-1.4040, 1.31, 19.60]}
            size={[0.2181, 0.65, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-1.4040, 1.75, 19.60]}
            size={[0.2181, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-1.4040, 1.72, 19.60]}
            size={[0.2181, 0.17, 0.65]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[-1.4040, 1.72, 19.60]}
            size={[0.6543, 0.17, 0.22]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[-1.4547, 1.32, 15.94]}
            size={[0.2227, 0.67, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-1.4547, 1.77, 15.94]}
            size={[0.2227, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-1.4547, 1.75, 15.94]}
            size={[0.2227, 0.18, 0.67]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-1.4547, 1.75, 15.94]}
            size={[0.6682, 0.18, 0.22]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[36.4645, 1.26, 39.93]}
            size={[0.2030, 0.61, 0.20]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[36.4645, 1.67, 39.93]}
            size={[0.2030, 0.20, 0.20]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[36.4645, 1.65, 39.93]}
            size={[0.2030, 0.16, 0.61]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[36.4645, 1.65, 39.93]}
            size={[0.6089, 0.16, 0.20]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[30.8066, 1.30, 35.81]}
            size={[0.2153, 0.65, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[30.8066, 1.73, 35.81]}
            size={[0.2153, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[30.8066, 1.71, 35.81]}
            size={[0.2153, 0.17, 0.65]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[30.8066, 1.71, 35.81]}
            size={[0.6458, 0.17, 0.22]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[40.1761, 1.30, 13.40]}
            size={[0.2164, 0.65, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[40.1761, 1.74, 13.40]}
            size={[0.2164, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[40.1761, 1.71, 13.40]}
            size={[0.2164, 0.17, 0.65]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[40.1761, 1.71, 13.40]}
            size={[0.6493, 0.17, 0.22]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[29.6893, 1.37, -14.05]}
            size={[0.2366, 0.71, 0.24]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[29.6893, 1.84, -14.05]}
            size={[0.2366, 0.24, 0.24]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[29.6893, 1.82, -14.05]}
            size={[0.2366, 0.19, 0.71]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[29.6893, 1.82, -14.05]}
            size={[0.7098, 0.19, 0.24]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[33.2664, 1.36, -15.44]}
            size={[0.2352, 0.71, 0.24]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[33.2664, 1.83, -15.44]}
            size={[0.2352, 0.24, 0.24]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[33.2664, 1.81, -15.44]}
            size={[0.2352, 0.19, 0.71]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[33.2664, 1.81, -15.44]}
            size={[0.7057, 0.19, 0.24]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[9.7606, 1.36, -26.77]}
            size={[0.2325, 0.70, 0.23]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[9.7606, 1.82, -26.77]}
            size={[0.2325, 0.23, 0.23]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[9.7606, 1.80, -26.77]}
            size={[0.2325, 0.19, 0.70]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[9.7606, 1.80, -26.77]}
            size={[0.6975, 0.19, 0.23]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[14.8959, 1.31, -12.30]}
            size={[0.2172, 0.65, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[14.8959, 1.74, -12.30]}
            size={[0.2172, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[14.8959, 1.72, -12.30]}
            size={[0.2172, 0.17, 0.65]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[14.8959, 1.72, -12.30]}
            size={[0.6517, 0.17, 0.22]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-28.3967, 1.30, 11.50]}
            size={[0.2169, 0.65, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-28.3967, 1.74, 11.50]}
            size={[0.2169, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-28.3967, 1.72, 11.50]}
            size={[0.2169, 0.17, 0.65]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[-28.3967, 1.72, 11.50]}
            size={[0.6507, 0.17, 0.22]}
            color={"#55aaff"}/>
        <Shape.Rect
            position={[-31.1877, 1.32, 8.90]}
            size={[0.2222, 0.67, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-31.1877, 1.77, 8.90]}
            size={[0.2222, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-31.1877, 1.74, 8.90]}
            size={[0.2222, 0.18, 0.67]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-31.1877, 1.74, 8.90]}
            size={[0.6665, 0.18, 0.22]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-23.3867, 1.34, 42.03]}
            size={[0.2268, 0.68, 0.23]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-23.3867, 1.79, 42.03]}
            size={[0.2268, 0.23, 0.23]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-23.3867, 1.77, 42.03]}
            size={[0.2268, 0.18, 0.68]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-23.3867, 1.77, 42.03]}
            size={[0.6805, 0.18, 0.23]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[4.0049, 1.26, 63.75]}
            size={[0.2035, 0.61, 0.20]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[4.0049, 1.67, 63.75]}
            size={[0.2035, 0.20, 0.20]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[4.0049, 1.65, 63.75]}
            size={[0.2035, 0.16, 0.61]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[4.0049, 1.65, 63.75]}
            size={[0.6106, 0.16, 0.20]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-29.3895, 1.34, -20.87]}
            size={[0.2277, 0.68, 0.23]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-29.3895, 1.80, -20.87]}
            size={[0.2277, 0.23, 0.23]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-29.3895, 1.77, -20.87]}
            size={[0.2277, 0.18, 0.68]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-29.3895, 1.77, -20.87]}
            size={[0.6832, 0.18, 0.23]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[70.3183, 1.36, 21.34]}
            size={[0.2328, 0.70, 0.23]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[70.3183, 1.82, 21.34]}
            size={[0.2328, 0.23, 0.23]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[70.3183, 1.80, 21.34]}
            size={[0.2328, 0.19, 0.70]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[70.3183, 1.80, 21.34]}
            size={[0.6984, 0.19, 0.23]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-2.4500, 1.30, -32.70]}
            size={[0.2147, 0.64, 0.21]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-2.4500, 1.73, -32.70]}
            size={[0.2147, 0.21, 0.21]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-2.4500, 1.71, -32.70]}
            size={[0.2147, 0.17, 0.64]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-2.4500, 1.71, -32.70]}
            size={[0.6440, 0.17, 0.21]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-0.0689, 1.29, -31.89]}
            size={[0.2129, 0.64, 0.21]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-0.0689, 1.72, -31.89]}
            size={[0.2129, 0.21, 0.21]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-0.0689, 1.70, -31.89]}
            size={[0.2129, 0.17, 0.64]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-0.0689, 1.70, -31.89]}
            size={[0.6388, 0.17, 0.21]}
            color={"#ff5959"}/>
        <Shape.Rect
            position={[-1.6266, 1.37, -30.02]}
            size={[0.2378, 0.71, 0.24]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-1.6266, 1.85, -30.02]}
            size={[0.2378, 0.24, 0.24]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-1.6266, 1.82, -30.02]}
            size={[0.2378, 0.19, 0.71]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-1.6266, 1.82, -30.02]}
            size={[0.7135, 0.19, 0.24]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-1.3725, 1.30, -26.34]}
            size={[0.2165, 0.65, 0.22]}
            color={"#55aa00"}/>
        <Shape.Rect
            position={[-1.3725, 1.74, -26.34]}
            size={[0.2165, 0.22, 0.22]}
            color={"#ffff00"}/>
        <Shape.Rect
            position={[-1.3725, 1.71, -26.34]}
            size={[0.2165, 0.17, 0.65]}
            color={"#da8541"}/>
        <Shape.Rect
            position={[-1.3725, 1.71, -26.34]}
            size={[0.6495, 0.17, 0.22]}
            color={"#da8541"}/>

    </group>
)
