import * as Shape from './SimpleShapes.jsx'

export const Workspace = () => (
    <group position={[2, 3, 0]}>
        <Shape.Baseplate/>
        // Autogenerated by export script. Time: 1760296406
        <Shape.RectCollider
            position={[24.500, 2.75, -32.50]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[24.500, 5.50, -32.50]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-16.000, 2.75, 8.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-16.000, 5.50, 8.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-31.500, 2.75, 24.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-31.500, 5.50, 24.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[27.500, 2.75, 12.50]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[27.500, 5.50, 12.50]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-11.500, 2.75, 59.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-11.500, 5.50, 59.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[75.500, 2.75, 100.50]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[75.500, 5.50, 100.50]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[59.500, 2.75, 42.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[59.500, 5.50, 42.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[47.000, 2.75, -16.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[47.000, 5.50, -16.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[42.000, 2.75, 1.50]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[42.000, 5.50, 1.50]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-20.500, 2.75, -27.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-20.500, 5.50, -27.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-22.000, 2.75, -5.50]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-22.000, 5.50, -5.50]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[23.000, 2.75, 48.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[23.000, 5.50, 48.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[39.000, 2.75, 24.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[39.000, 5.50, 24.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-5.000, 2.75, -14.50]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-5.000, 5.50, -14.50]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[-9.500, 2.75, 31.00]}
            size={[1.000, 4.50, 1.00]}
            color={"#7c5c46"}/>
        <Shape.Rect
            position={[-9.500, 5.50, 31.00]}
            size={[2.500, 2.50, 2.50]}
            color={"#77d365"}/>
        <Shape.RectCollider
            position={[9.500, 3.87, 27.00]}
            size={[12.000, 6.75, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[11.750, 2.87, 28.25]}
            size={[2.500, 4.75, 1.00]}
            color={"#444e61"}/>
        <Shape.Rect
            position={[7.375, 7.50, 27.00]}
            size={[6.250, 0.50, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[3.250, 1.37, 27.50]}
            size={[2.500, 1.75, 2.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[4.000, 1.12, 25.75]}
            size={[1.000, 1.25, 2.00]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[11.250, 0.87, 29.00]}
            size={[3.500, 0.75, 2.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[15.000, 0.87, 26.00]}
            size={[2.000, 0.75, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[12.250, 1.62, 28.75]}
            size={[2.500, 2.25, 2.00]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[3.500, 2.12, 26.00]}
            size={[1.000, 3.25, 1.50]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[6.000, 1.12, 28.00]}
            size={[3.000, 1.25, 0.50]}
            color={"#444e61"}/>
        <Shape.Rect
            position={[11.750, 7.37, 27.25]}
            size={[2.500, 0.25, 1.00]}
            color={"#444e61"}/>
        <Shape.RectCollider
            position={[15.500, 1.37, 26.50]}
            size={[2.000, 1.75, 1.50]}
            color={"#444e61"}/>

    </group>
)
